// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoycoypkyqxrcqdpfqhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFveWNveXBreXF4cmNxZHBmcWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NTQ4NDgsImV4cCI6MjA1NzUzMDg0OH0.jo6NteN468r_mKPB2rCoOuNNLu-LT9M3lxV3wv-Z2Jo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);